#!/bin/bash
# kernel_hardening.sh - Kernel security hardening for BrainVault Elite

apply_kernel_hardening() {
    log_section "⚙️ Applying Kernel Security Hardening"
    
    local sysctl_conf="/etc/sysctl.d/99-brainvault-hardening.conf"
    
    if is_dryrun; then
        add_dryrun_operation "KERNEL" "Create kernel hardening configuration"
        add_dryrun_operation "KERNEL" "Apply sysctl security parameters"
        return 0
    fi
    
    log_info "Creating kernel hardening configuration..."
    
    cat > "$sysctl_conf" <<'EOF'
# BrainVault Elite - Kernel Security Hardening
# Generated by brainvault_elite.sh

# Network Security
# ----------------

# IP Forwarding (disable unless router)
net.ipv4.ip_forward = 0
net.ipv6.conf.all.forwarding = 0

# SYN Cookies (protect against SYN flood attacks)
net.ipv4.tcp_syncookies = 1

# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Ignore source-routed packets
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Ignore send redirects
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Reverse path filtering
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Log martians (packets with impossible addresses)
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Ignore ICMP ping requests (optional - commented by default)
# net.ipv4.icmp_echo_ignore_all = 1

# Ignore broadcast pings
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Ignore bogus ICMP error responses
net.ipv4.icmp_ignore_bogus_error_responses = 1

# TCP/IP stack hardening
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_syn_retries = 3
net.ipv4.tcp_synack_retries = 2

# Memory Protection
# -----------------

# Address Space Layout Randomization (ASLR)
kernel.randomize_va_space = 2

# Restrict access to kernel logs
kernel.dmesg_restrict = 1

# Restrict access to kernel pointers
kernel.kptr_restrict = 2

# Restrict kernel performance events
kernel.perf_event_paranoid = 3

# Disable kexec (prevents replacing running kernel)
kernel.kexec_load_disabled = 1

# Restrict ptrace (debugging) to same user
kernel.yama.ptrace_scope = 1

# File System Protection
# ----------------------

# Protect symlinks and hardlinks
fs.protected_symlinks = 1
fs.protected_hardlinks = 1
fs.protected_fifos = 2
fs.protected_regular = 2

# Increase inotify limits for better file monitoring
fs.inotify.max_user_watches = 524288
fs.inotify.max_queued_events = 32768

# Core dumps
# ----------

# Restrict core dumps to setuid programs
fs.suid_dumpable = 0
EOF
    
    log_success "Kernel hardening configuration created at $sysctl_conf"
    
    # Apply the settings
    safe_exec "Applying kernel hardening" sysctl --system
    
    # Verify some critical settings
    verify_kernel_settings
    
    log_success "Kernel hardening applied successfully"
}

verify_kernel_settings() {
    log_info "Verifying critical kernel settings..."
    
    local settings=(
        "net.ipv4.tcp_syncookies"
        "kernel.randomize_va_space"
        "kernel.dmesg_restrict"
        "fs.protected_symlinks"
    )
    
    for setting in "${settings[@]}"; do
        local value=$(sysctl -n "$setting" 2>/dev/null)
        if [[ -n "$value" ]]; then
            log_debug "$setting = $value"
        else
            log_warn "Could not verify: $setting"
        fi
    done
    
    log_success "Kernel settings verified"
}

# Apply additional hardening for secure mode
apply_secure_mode_hardening() {
    log_section "🔒 Applying Enhanced Security Hardening"
    
    if is_dryrun; then
        add_dryrun_operation "KERNEL" "Apply enhanced security settings"
        add_dryrun_operation "KERNEL" "Restrict kernel modules loading"
        return 0
    fi
    
    local secure_conf="/etc/sysctl.d/99-brainvault-secure.conf"
    
    cat > "$secure_conf" <<'EOF'
# BrainVault Elite - Enhanced Security Mode
# WARNING: These settings may break some applications

# Disable all ICMP
net.ipv4.icmp_echo_ignore_all = 1

# Strict reverse path filtering
net.ipv4.conf.all.rp_filter = 2
net.ipv4.conf.default.rp_filter = 2

# Disable IPv6 (if not needed)
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1

# Restrict kernel module loading
kernel.modules_disabled = 0  # Set to 1 to completely lock (IRREVERSIBLE until reboot)

# Maximum PID value (helps prevent PID exhaustion attacks)
kernel.pid_max = 65536

# Restrict BPF JIT compiler
net.core.bpf_jit_harden = 2
EOF
    
    safe_exec "Applying secure mode hardening" sysctl --system
    
    log_success "Enhanced security hardening applied"
}

# Disable unused network protocols
disable_unused_protocols() {
    log_info "Disabling unused network protocols..."
    
    if is_dryrun; then
        add_dryrun_operation "KERNEL" "Disable unused network protocols"
        return 0
    fi
    
    local protocols_conf="/etc/modprobe.d/brainvault-protocols.conf"
    
    cat > "$protocols_conf" <<'EOF'
# Disable unused network protocols
install dccp /bin/true
install sctp /bin/true
install rds /bin/true
install tipc /bin/true
EOF
    
    log_success "Unused protocols disabled"
}

# Export functions
export -f apply_kernel_hardening
export -f verify_kernel_settings
export -f apply_secure_mode_hardening
export -f disable_unused_protocols
